# Generated by Django 2.2.5 on 2019-11-07 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manageItems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restauran_location', models.CharField(max_length=20)),
                ('global_menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manageItems.GlobalMenu')),
            ],
        ),
    ]
