# Generated by Django 2.2.5 on 2019-11-07 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_menu_name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=200)),
                ('item_price', models.PositiveIntegerField(default=0)),
                ('item_img', models.FileField(null=True, upload_to='img')),
                ('global_menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manageItems.GlobalMenu')),
            ],
        ),
    ]
